"use client";

import { Activity, CheckCircle2, Clock, Cpu, DollarSign } from "lucide-react";
import { Card, CardContent } from "@/components/ui/Card";
import { api } from "@/lib/api/client";
import { DataState, useApiData } from "@/lib/api/useApiData";

export default function AgentsPage() {
  const { data, loading, error } = useApiData(api.runs);
  const runs = data?.runs || [];
  const totalTokens = runs.reduce((total, run) => total + (run.total_tokens || 0), 0);
  const totalCost = runs.reduce((total, run) => total + (run.total_cost_usd || 0), 0);
  return <div className="space-y-6 pb-12"><div className="flex justify-between items-end"><div><h1 className="text-[32px] font-semibold tracking-tight">Agent Traces</h1><p className="text-[var(--text-secondary)] mt-1">Persisted workflow runs, provider usage, and outcomes</p></div><div className="text-right"><p className="text-sm text-[var(--text-secondary)]">Displayed run cost</p><p className="font-mono text-xl font-bold">${totalCost.toFixed(2)}</p></div></div><DataState loading={loading} error={error} empty={!data || runs.length === 0}><div className="grid grid-cols-1 md:grid-cols-4 gap-6"><Metric icon={<Cpu />} label="Runs" value={data?.total} /><Metric icon={<CheckCircle2 />} label="Completed" value={runs.filter(run => run.status === "completed").length} /><Metric icon={<Clock />} label="Provider tokens" value={totalTokens.toLocaleString()} /><Metric icon={<DollarSign />} label="Visible run cost" value={`$${totalCost.toFixed(2)}`} /></div><Card><div className="p-5 border-b bg-white rounded-t-2xl flex items-center"><Activity className="w-5 h-5 mr-2 text-[var(--primary)]" /><h3 className="font-semibold">Workflow runs</h3></div><div className="overflow-x-auto bg-white"><table className="w-full text-left"><thead><tr className="bg-[var(--surface-subtle)] text-xs uppercase text-[var(--text-secondary)]"><th className="px-6 py-3">Run</th><th className="px-6 py-3">Workflow</th><th className="px-6 py-3">Stage</th><th className="px-6 py-3">Obligations</th><th className="px-6 py-3">Tokens</th><th className="px-6 py-3">Cost</th><th className="px-6 py-3">Status</th></tr></thead><tbody className="divide-y text-sm">{runs.map(run => <tr key={run.id}><td className="px-6 py-4 font-mono text-xs">{run.id.slice(0, 13)}</td><td className="px-6 py-4">{run.workflow_type}</td><td className="px-6 py-4">{run.current_stage || "—"}</td><td className="px-6 py-4">{run.total_obligations ?? "—"}</td><td className="px-6 py-4">{run.total_tokens?.toLocaleString() ?? "—"}</td><td className="px-6 py-4">{run.total_cost_usd == null ? "—" : `$${run.total_cost_usd.toFixed(2)}`}</td><td className="px-6 py-4 uppercase text-xs font-bold">{run.status}</td></tr>)}</tbody></table></div></Card></DataState></div>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number | undefined }) { return <Card><CardContent className="p-5 flex justify-between"><div><p className="text-sm text-[var(--text-secondary)]">{label}</p><p className="text-2xl font-semibold mt-2">{value ?? "—"}</p></div><div className="p-3 bg-[var(--surface-subtle)] rounded-xl text-[var(--primary)]">{icon}</div></CardContent></Card>; }
