"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/Card";
import { Activity, CheckSquare, FileText, ShieldAlert } from "lucide-react";
import { api } from "@/lib/api/client";
import { DataState, usePublicApiData } from "@/lib/api/useApiData";

export default function DashboardPage() {
  const { data, loading, error } = usePublicApiData(api.dashboard);
  const dashboard = data;
  return <div className="space-y-8 pb-12"><div className="flex justify-between items-end"><div><h1 className="text-[32px] font-semibold tracking-tight text-[var(--text-primary)]">Dashboard</h1><p className="text-[var(--text-secondary)] mt-1">Live, persisted compliance intelligence</p></div><div className="flex items-center space-x-2 text-sm text-[var(--text-secondary)] bg-white px-4 py-2 rounded-full border border-[var(--border-subtle)] shadow-sm"><div className="w-2 h-2 rounded-full bg-[var(--success)]" /><span className="font-medium">Live API</span></div></div><DataState loading={loading} error={error} empty={!dashboard}>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"><StatCard title="Documents" value={dashboard?.documents.length} icon={<FileText className="text-[var(--primary)] w-5 h-5" />} /><StatCard title="Obligations" value={dashboard?.obligation_total} icon={<CheckSquare className="text-[var(--secondary-brand)] w-5 h-5" />} /><StatCard title="Detected changes" value={dashboard?.diff_change_total} icon={<ShieldAlert className="text-[var(--warning)] w-5 h-5" />} /><StatCard title="Evaluation F1" value={dashboard?.evaluation_f1?.toFixed(2)} icon={<Activity className="text-[var(--accent-blue)] w-5 h-5" />} /></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card className="lg:col-span-2"><CardHeader className="border-b border-[var(--border-subtle)] pb-4"><CardTitle>Persisted documents</CardTitle><CardDescription>Public regulatory circulars available in the live corpus</CardDescription></CardHeader><CardContent className="pt-6 space-y-3">{dashboard?.documents.map(document => <div key={document.id} className="flex justify-between p-4 rounded-xl border border-[var(--border-subtle)]"><div><p className="font-medium">{document.title}</p><p className="text-xs text-[var(--text-secondary)] mt-1">{document.reference_number || "—"}</p></div><div className="text-right"><span className="text-xs uppercase font-medium">{document.status}</span><p className="text-xs text-[var(--text-muted)] mt-2">{document.page_count ?? "—"} pages</p></div></div>)}</CardContent></Card><Card><CardHeader className="border-b border-[var(--border-subtle)] pb-4"><CardTitle>Evaluation headline</CardTitle><CardDescription>Latest completed evaluation</CardDescription></CardHeader><CardContent className="pt-6 space-y-4"><div><p className="text-3xl font-semibold">{dashboard?.evaluation_f1?.toFixed(2) ?? "—"}</p><p className="text-xs text-[var(--text-secondary)] mt-1">F1, coverage matcher</p></div><div className="border-t pt-4 text-sm text-[var(--text-secondary)]">Confidence interval: {dashboard?.evaluation_ci ? JSON.stringify(dashboard.evaluation_ci) : "—"}</div><div className="border-t pt-4 text-sm text-[var(--text-secondary)]">Operational views remain available to authorized users.</div></CardContent></Card></div>
  </DataState></div>;
}

function StatCard({ title, value, icon }: { title: string; value: string | number | null | undefined; icon: React.ReactNode }) { return <Card><CardContent className="p-6 flex justify-between"><div><p className="text-sm font-medium text-[var(--text-secondary)]">{title}</p><h2 className="text-[28px] font-semibold mt-4">{value ?? "—"}</h2></div><div className="p-2 bg-[var(--surface-subtle)] rounded-lg">{icon}</div></CardContent></Card>; }
