"use client";

import { useState } from "react";
import { AlertTriangle, GitCommit } from "lucide-react";
import { Card, CardContent } from "@/components/ui/Card";
import { api, Change, Diff } from "@/lib/api/client";
import { DataState, useApiData } from "@/lib/api/useApiData";
import { cn } from "@/lib/utils";

export default function ChangesPage() {
  const { data, loading, error } = useApiData<Diff | null>(async () => { const runs = await api.diffRuns(); return runs.diff_runs[0] ? api.diff(runs.diff_runs[0].diff_run_id) : null; });
  const [selected, setSelected] = useState<Change | null>(null);
  const summary = data?.summary || {};
  return <div className="space-y-6 pb-12"><div><h1 className="text-[32px] font-semibold tracking-tight">Regulatory Changes</h1><p className="text-[var(--text-secondary)] mt-1">Persisted deterministic diff against the latest circular</p></div><DataState loading={loading} error={error} empty={!data || data.changes.length === 0}><div className="grid grid-cols-1 lg:grid-cols-4 gap-6"><SummaryCard label="Created" value={summary.created} /><SummaryCard label="Modified" value={summary.modified} /><SummaryCard label="Removed" value={summary.removed} /><SummaryCard label="Requires confirmation" value={data?.changes.filter(change => change.requires_confirmation).length} /></div><div className="space-y-4">{data?.changes.map(change => <button key={change.id} onClick={() => setSelected(change)} className="w-full text-left"><Card className="hover:border-[var(--primary)] transition-all"><CardContent className="p-5"><div className="flex justify-between gap-4"><div className="flex gap-3"><GitCommit className="mt-1 text-[var(--primary)]" size={18} /><div><div className="flex items-center gap-2"><TypeBadge value={change.change_type} /><TypeBadge value={change.materiality || "none"} /><span className="text-xs text-[var(--text-muted)]">{change.requires_confirmation ? "Requires confirmation" : "Deterministic"}</span></div><p className="font-semibold mt-3">{change.obligation || change.new_ref || change.old_ref || "Persisted regulatory change"}</p><div className="mt-3 flex flex-wrap gap-2">{change.materiality_reasons.map(reason => <span key={reason} className="text-[11px] px-2 py-1 bg-[var(--surface-subtle)] border rounded">{reason}</span>)}</div></div></div><span className="text-xs font-mono text-[var(--text-muted)]">{change.id.slice(0, 13)}</span></div></CardContent></Card></button>)}</div></DataState>{selected && <ChangeDetail change={selected} close={() => setSelected(null)} />}</div>;
}

function SummaryCard({ label, value }: { label: string; value: number | undefined }) { return <Card><CardContent className="p-5"><div className="flex items-center gap-2 text-[var(--primary)]"><AlertTriangle size={16} /><span className="text-sm font-semibold">{label}</span></div><p className="text-3xl font-bold mt-3">{value ?? "—"}</p></CardContent></Card>; }
function TypeBadge({ value }: { value: string }) { const tone = value === "created" ? "bg-[#ECFDF5] text-[#059669]" : value === "modified" ? "bg-[#EFF6FF] text-[#2563EB]" : value === "high" ? "bg-[#FEF2F2] text-[#DC2626]" : "bg-[var(--surface-subtle)] text-[var(--text-secondary)]"; return <span className={cn("text-[10px] uppercase font-bold px-2 py-0.5 rounded", tone)}>{value}</span>; }
function ChangeDetail({ change, close }: { change: Change; close: () => void }) { return <div className="fixed inset-0 bg-black/20 z-50 flex justify-end"><aside className="w-full max-w-xl bg-white h-full shadow-xl p-6 overflow-y-auto"><button onClick={close} className="text-sm text-[var(--primary)]">Close</button><h2 className="text-xl font-semibold mt-4">{change.change_type} change</h2><p className="mt-3 text-sm">{change.obligation || "—"}</p>{change.change_type === "modified" ? <div className="grid grid-cols-2 gap-4 mt-6"><TextPanel label="Previous" text={change.old_text} /><TextPanel label="Current" text={change.new_text} /></div> : <TextPanel label="Source citation" text={change.new_text || String(change.citations.new || "—")} />}{change.changed_fields.length > 0 && <div className="mt-6"><p className="text-xs uppercase font-bold text-[var(--text-muted)]">Changed fields</p><div className="flex flex-wrap gap-2 mt-2">{change.changed_fields.map(field => <span key={field} className="text-xs border rounded px-2 py-1">{field}</span>)}</div></div>}</aside></div>; }
function TextPanel({ label, text }: { label: string; text: string | null }) { return <div className="mt-6"><p className="text-xs uppercase font-bold text-[var(--text-muted)]">{label}</p><p className="mt-2 p-4 bg-[var(--surface-subtle)] border rounded-lg text-sm leading-relaxed">{text || "—"}</p></div>; }
