"""initial schema

Revision ID: 6ebd241e922e
Revises: 
Create Date: 2026-08-07 01:52:54.570396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ebd241e922e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('example_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_datasets'))
    )
    op.create_index('ix_evalds_active', 'evaluation_datasets', ['is_active'], unique=False)
    op.create_index('ix_evalds_type', 'evaluation_datasets', ['dataset_type'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('sebi_registration_number', sa.String(length=50), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_index('ix_organizations_active', 'organizations', ['is_active'], unique=False)
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=200), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions'))
    )
    op.create_index('ix_prompt_active', 'prompt_versions', ['is_active'], unique=False)
    op.create_index('ix_prompt_name_version', 'prompt_versions', ['name', 'version'], unique=True)
    op.create_index('ix_prompt_task', 'prompt_versions', ['task'], unique=False)
    op.create_table('regulatory_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('discovery_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_interval_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulatory_sources'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_org', 'audit_events', ['organization_id'], unique=False)
    op.create_index('ix_audit_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_events', ['timestamp'], unique=False)
    op.create_index('ix_audit_user', 'audit_events', ['user_id'], unique=False)
    op.create_table('controls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('control_type', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('effectiveness', sa.String(length=50), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_controls_organization_id_organizations')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_controls_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_controls'))
    )
    op.create_index('ix_control_dept', 'controls', ['department'], unique=False)
    op.create_index('ix_control_org', 'controls', ['organization_id'], unique=False)
    op.create_index('ix_control_status', 'controls', ['status'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('ndcg', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_examples', sa.Integer(), nullable=True),
    sa.Column('passed_examples', sa.Integer(), nullable=True),
    sa.Column('failed_examples', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], name=op.f('fk_evaluation_runs_dataset_id_evaluation_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs'))
    )
    op.create_index('ix_evalrun_dataset', 'evaluation_runs', ['dataset_id'], unique=False)
    op.create_index('ix_evalrun_status', 'evaluation_runs', ['status'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='ID of the referenced domain entity'),
    sa.Column('label', sa.String(length=1000), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_graph_nodes_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_nodes'))
    )
    op.create_index('ix_gnode_entity', 'graph_nodes', ['entity_id'], unique=False)
    op.create_index('ix_gnode_org', 'graph_nodes', ['organization_id'], unique=False)
    op.create_index('ix_gnode_type', 'graph_nodes', ['node_type'], unique=False)
    op.create_index('ix_gnode_type_entity', 'graph_nodes', ['node_type', 'entity_id'], unique=True)
    op.create_table('organization_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ORG_ADMIN', 'COMPLIANCE_OFFICER', 'REVIEWER', 'ANALYST', 'AUDITOR', 'SUPERVISORY_VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_memberships')),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership_user_org')
    )
    op.create_index('ix_membership_org', 'organization_memberships', ['organization_id'], unique=False)
    op.create_index('ix_membership_user', 'organization_memberships', ['user_id'], unique=False)
    op.create_table('processes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_processes_organization_id_organizations')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_processes_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processes'))
    )
    op.create_index('ix_process_org', 'processes', ['organization_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_token_expires', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_token_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('regulatory_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True, comment='NULL for globally shared regulatory documents'),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('reference_number', sa.String(length=200), nullable=True),
    sa.Column('document_type', sa.Enum('MASTER_CIRCULAR', 'CIRCULAR', 'AMENDMENT', 'NOTIFICATION', 'GUIDELINE', 'ORDER', 'PRESS_RELEASE', 'CONSULTATION_PAPER', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('regulatory_domain', sa.Enum('MARKET_INTERMEDIARIES', 'MUTUAL_FUNDS', 'CORPORATE_FINANCE', 'MARKET_REGULATION', 'LEGAL_AFFAIRS', 'INVESTMENT_MANAGEMENT', 'DEBT_AND_HYBRID', 'ALTERNATIVE_INVESTMENT', 'OTHER', name='regulatorydomain'), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('download_url', sa.String(length=2000), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('applicable_to', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'DOWNLOADED', 'PARSING', 'PARSED', 'STRUCTURING', 'STRUCTURED', 'CLASSIFYING', 'CLASSIFIED', 'READY', 'PROCESSING', 'PROCESSED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('parsing_quality_score', sa.Float(), nullable=True),
    sa.Column('ocr_applied', sa.Boolean(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('metadata_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_regulatory_documents_organization_id_organizations')),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_sources.id'], name=op.f('fk_regulatory_documents_source_id_regulatory_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulatory_documents'))
    )
    op.create_index('ix_doc_domain', 'regulatory_documents', ['regulatory_domain'], unique=False)
    op.create_index('ix_doc_hash', 'regulatory_documents', ['sha256_hash'], unique=False)
    op.create_index('ix_doc_org', 'regulatory_documents', ['organization_id'], unique=False)
    op.create_index('ix_doc_ref', 'regulatory_documents', ['reference_number'], unique=False)
    op.create_index('ix_doc_status', 'regulatory_documents', ['status'], unique=False)
    op.create_index('ix_doc_type', 'regulatory_documents', ['document_type'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('ocr_content', sa.Text(), nullable=True),
    sa.Column('has_tables', sa.Boolean(), nullable=False),
    sa.Column('has_images', sa.Boolean(), nullable=False),
    sa.Column('tables_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['regulatory_documents.id'], name=op.f('fk_document_pages_document_id_regulatory_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_page_doc_num')
    )
    op.create_index('ix_page_doc', 'document_pages', ['document_id'], unique=False)
    op.create_table('document_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('target_document_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['regulatory_documents.id'], name=op.f('fk_document_relationships_source_document_id_regulatory_documents')),
    sa.ForeignKeyConstraint(['target_document_id'], ['regulatory_documents.id'], name=op.f('fk_document_relationships_target_document_id_regulatory_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_relationships'))
    )
    op.create_index('ix_docrel_source', 'document_relationships', ['source_document_id'], unique=False)
    op.create_index('ix_docrel_target', 'document_relationships', ['target_document_id'], unique=False)
    op.create_index('ix_docrel_type', 'document_relationships', ['relationship_type'], unique=False)
    op.create_table('document_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('section_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['regulatory_documents.id'], name=op.f('fk_document_sections_document_id_regulatory_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_section_id'], ['document_sections.id'], name=op.f('fk_document_sections_parent_section_id_document_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sections'))
    )
    op.create_index('ix_section_doc', 'document_sections', ['document_id'], unique=False)
    op.create_index('ix_section_parent', 'document_sections', ['parent_section_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('workflow_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'WAITING_HUMAN', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowstatus'), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('total_clauses', sa.Integer(), nullable=True),
    sa.Column('total_obligations', sa.Integer(), nullable=True),
    sa.Column('approved_obligations', sa.Integer(), nullable=True),
    sa.Column('rejected_obligations', sa.Integer(), nullable=True),
    sa.Column('review_pending', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('checkpoint_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('celery_task_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['regulatory_documents.id'], name=op.f('fk_extraction_runs_document_id_regulatory_documents')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_extraction_runs_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_runs'))
    )
    op.create_index('ix_run_doc', 'extraction_runs', ['document_id'], unique=False)
    op.create_index('ix_run_org', 'extraction_runs', ['organization_id'], unique=False)
    op.create_index('ix_run_status', 'extraction_runs', ['status'], unique=False)
    op.create_index('ix_run_type', 'extraction_runs', ['workflow_type'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_source_node_id_graph_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_target_node_id_graph_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges'))
    )
    op.create_index('ix_gedge_source', 'graph_edges', ['source_node_id'], unique=False)
    op.create_index('ix_gedge_source_type', 'graph_edges', ['source_node_id', 'relationship_type'], unique=False)
    op.create_index('ix_gedge_target', 'graph_edges', ['target_node_id'], unique=False)
    op.create_index('ix_gedge_target_type', 'graph_edges', ['target_node_id', 'relationship_type'], unique=False)
    op.create_index('ix_gedge_type', 'graph_edges', ['relationship_type'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRYING', 'SKIPPED', name='agentstatus'), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=True),
    sa.Column('validation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], name=op.f('fk_agent_runs_extraction_run_id_extraction_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_run_extraction', 'agent_runs', ['extraction_run_id'], unique=False)
    op.create_index('ix_agent_run_name', 'agent_runs', ['agent_name'], unique=False)
    op.create_index('ix_agent_run_status', 'agent_runs', ['status'], unique=False)
    op.create_table('clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('parent_clause_id', sa.UUID(), nullable=True),
    sa.Column('clause_number', sa.String(length=50), nullable=True),
    sa.Column('clause_type', sa.Enum('OBLIGATION', 'PROHIBITION', 'PERMISSION', 'EXEMPTION', 'DEFINITION', 'DEADLINE', 'PENALTY', 'REPORTING_REQUIREMENT', 'RECORDKEEPING_REQUIREMENT', 'DISCLOSURE_REQUIREMENT', 'PROCEDURAL_INSTRUCTION', 'CONTEXTUAL_STATEMENT', 'UNKNOWN', name='clausetype'), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('heading', sa.String(length=1000), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['regulatory_documents.id'], name=op.f('fk_clauses_document_id_regulatory_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_clause_id'], ['clauses.id'], name=op.f('fk_clauses_parent_clause_id_clauses')),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], name=op.f('fk_clauses_section_id_document_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clauses'))
    )
    op.create_index('ix_clause_doc', 'clauses', ['document_id'], unique=False)
    op.create_index('ix_clause_parent', 'clauses', ['parent_clause_id'], unique=False)
    op.create_index('ix_clause_section', 'clauses', ['section_id'], unique=False)
    op.create_index('ix_clause_type', 'clauses', ['clause_type'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], name=op.f('fk_workflow_events_extraction_run_id_extraction_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_events'))
    )
    op.create_index('ix_event_run', 'workflow_events', ['extraction_run_id'], unique=False)
    op.create_index('ix_event_timestamp', 'workflow_events', ['timestamp'], unique=False)
    op.create_index('ix_event_type', 'workflow_events', ['event_type'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_steps_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_steps'))
    )
    op.create_index('ix_step_agent_run', 'agent_steps', ['agent_run_id'], unique=False)
    op.create_index('ix_step_type', 'agent_steps', ['step_type'], unique=False)
    op.create_table('clause_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], name=op.f('fk_clause_embeddings_clause_id_clauses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['regulatory_documents.id'], name=op.f('fk_clause_embeddings_document_id_regulatory_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clause_embeddings'))
    )
    op.create_index('ix_cembed_clause', 'clause_embeddings', ['clause_id'], unique=False)
    op.create_index('ix_cembed_doc', 'clause_embeddings', ['document_id'], unique=False)
    op.create_index('ix_cembed_model', 'clause_embeddings', ['embedding_model'], unique=False)
    op.create_table('evaluation_examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_clause_id', sa.UUID(), nullable=True),
    sa.Column('annotator_id', sa.UUID(), nullable=True),
    sa.Column('annotator_notes', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['users.id'], name=op.f('fk_evaluation_examples_annotator_id_users')),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], name=op.f('fk_evaluation_examples_dataset_id_evaluation_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_clause_id'], ['clauses.id'], name=op.f('fk_evaluation_examples_source_clause_id_clauses')),
    sa.ForeignKeyConstraint(['source_document_id'], ['regulatory_documents.id'], name=op.f('fk_evaluation_examples_source_document_id_regulatory_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_examples'))
    )
    op.create_index('ix_evalex_dataset', 'evaluation_examples', ['dataset_id'], unique=False)
    op.create_table('model_invocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('system_prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('response_format', sa.String(length=50), nullable=True),
    sa.Column('was_structured', sa.Boolean(), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_model_invocations_agent_run_id_agent_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_invocations'))
    )
    op.create_index('ix_invocation_agent', 'model_invocations', ['agent_run_id'], unique=False)
    op.create_index('ix_invocation_model', 'model_invocations', ['model_name'], unique=False)
    op.create_index('ix_invocation_provider', 'model_invocations', ['provider'], unique=False)
    op.create_index('ix_invocation_task', 'model_invocations', ['task_type'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True, comment='NULL for global obligations from shared documents'),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('normalized_obligation', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=500), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('object', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('deadline_description', sa.Text(), nullable=True),
    sa.Column('evidence_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('record_retention_requirement', sa.Text(), nullable=True),
    sa.Column('penalty_reference', sa.Text(), nullable=True),
    sa.Column('cross_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('responsible_department', sa.String(length=255), nullable=True),
    sa.Column('affected_controls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_processes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='risklevel'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=100), nullable=True),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('citation_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('validation_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('CANDIDATE', 'VALIDATED', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'SUPERSEDED', 'ARCHIVED', name='obligationstatus'), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], name=op.f('fk_obligations_clause_id_clauses')),
    sa.ForeignKeyConstraint(['document_id'], ['regulatory_documents.id'], name=op.f('fk_obligations_document_id_regulatory_documents')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_obligations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_obligations_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obligations'))
    )
    op.create_index('ix_obl_clause', 'obligations', ['clause_id'], unique=False)
    op.create_index('ix_obl_confidence', 'obligations', ['confidence'], unique=False)
    op.create_index('ix_obl_deadline', 'obligations', ['deadline'], unique=False)
    op.create_index('ix_obl_doc', 'obligations', ['document_id'], unique=False)
    op.create_index('ix_obl_extraction_run', 'obligations', ['extraction_run_id'], unique=False)
    op.create_index('ix_obl_org', 'obligations', ['organization_id'], unique=False)
    op.create_index('ix_obl_risk', 'obligations', ['risk_level'], unique=False)
    op.create_index('ix_obl_status', 'obligations', ['status'], unique=False)
    op.create_table('compliance_calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=200), nullable=True),
    sa.Column('responsible_department', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('evidence_status', sa.String(length=50), nullable=True),
    sa.Column('implementation_status', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_compliance_calendar_events_obligation_id_obligations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_compliance_calendar_events_organization_id_organizations')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_compliance_calendar_events_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_calendar_events'))
    )
    op.create_index('ix_cal_date', 'compliance_calendar_events', ['event_date'], unique=False)
    op.create_index('ix_cal_obl', 'compliance_calendar_events', ['obligation_id'], unique=False)
    op.create_index('ix_cal_org', 'compliance_calendar_events', ['organization_id'], unique=False)
    op.create_index('ix_cal_type', 'compliance_calendar_events', ['event_type'], unique=False)
    op.create_table('compliance_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('change_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='taskstatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_compliance_tasks_assigned_to_users')),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_compliance_tasks_obligation_id_obligations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_compliance_tasks_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_tasks'))
    )
    op.create_index('ix_task_assigned', 'compliance_tasks', ['assigned_to'], unique=False)
    op.create_index('ix_task_obl', 'compliance_tasks', ['obligation_id'], unique=False)
    op.create_index('ix_task_org', 'compliance_tasks', ['organization_id'], unique=False)
    op.create_index('ix_task_status', 'compliance_tasks', ['status'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=False),
    sa.Column('example_id', sa.UUID(), nullable=False),
    sa.Column('predicted_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], name=op.f('fk_evaluation_results_evaluation_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['example_id'], ['evaluation_examples.id'], name=op.f('fk_evaluation_results_example_id_evaluation_examples')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_results'))
    )
    op.create_index('ix_evalresult_example', 'evaluation_results', ['example_id'], unique=False)
    op.create_index('ix_evalresult_run', 'evaluation_results', ['evaluation_run_id'], unique=False)
    op.create_table('evidence_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_frequency', sa.String(length=100), nullable=True),
    sa.Column('validity_period_days', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_evidence_requirements_obligation_id_obligations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evidence_requirements_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_requirements'))
    )
    op.create_index('ix_evreq_obl', 'evidence_requirements', ['obligation_id'], unique=False)
    op.create_index('ix_evreq_org', 'evidence_requirements', ['organization_id'], unique=False)
    op.create_table('obligation_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('cited_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('clause_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], name=op.f('fk_obligation_citations_clause_id_clauses')),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_obligation_citations_obligation_id_obligations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obligation_citations'))
    )
    op.create_index('ix_citation_field', 'obligation_citations', ['field_name'], unique=False)
    op.create_index('ix_citation_obl', 'obligation_citations', ['obligation_id'], unique=False)
    op.create_table('obligation_control_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], name=op.f('fk_obligation_control_mappings_control_id_controls')),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_obligation_control_mappings_obligation_id_obligations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_obligation_control_mappings_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obligation_control_mappings'))
    )
    op.create_index('ix_ocm_control', 'obligation_control_mappings', ['control_id'], unique=False)
    op.create_index('ix_ocm_obl', 'obligation_control_mappings', ['obligation_id'], unique=False)
    op.create_index('ix_ocm_org', 'obligation_control_mappings', ['organization_id'], unique=False)
    op.create_table('regulatory_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('old_document_id', sa.UUID(), nullable=True),
    sa.Column('new_document_id', sa.UUID(), nullable=False),
    sa.Column('old_clause_id', sa.UUID(), nullable=True),
    sa.Column('new_clause_id', sa.UUID(), nullable=True),
    sa.Column('old_obligation_id', sa.UUID(), nullable=True),
    sa.Column('new_obligation_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.Enum('CREATED', 'MODIFIED', 'REMOVED', 'SUPERSEDED', 'DEADLINE_CHANGED', 'APPLICABILITY_CHANGED', 'ACTOR_CHANGED', 'EVIDENCE_REQUIREMENT_CHANGED', 'PENALTY_CHANGED', 'EXCEPTION_CHANGED', name='changetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('old_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('diff_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['new_clause_id'], ['clauses.id'], name=op.f('fk_regulatory_changes_new_clause_id_clauses')),
    sa.ForeignKeyConstraint(['new_document_id'], ['regulatory_documents.id'], name=op.f('fk_regulatory_changes_new_document_id_regulatory_documents')),
    sa.ForeignKeyConstraint(['new_obligation_id'], ['obligations.id'], name=op.f('fk_regulatory_changes_new_obligation_id_obligations')),
    sa.ForeignKeyConstraint(['old_clause_id'], ['clauses.id'], name=op.f('fk_regulatory_changes_old_clause_id_clauses')),
    sa.ForeignKeyConstraint(['old_document_id'], ['regulatory_documents.id'], name=op.f('fk_regulatory_changes_old_document_id_regulatory_documents')),
    sa.ForeignKeyConstraint(['old_obligation_id'], ['obligations.id'], name=op.f('fk_regulatory_changes_old_obligation_id_obligations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulatory_changes'))
    )
    op.create_index('ix_change_new_doc', 'regulatory_changes', ['new_document_id'], unique=False)
    op.create_index('ix_change_old_doc', 'regulatory_changes', ['old_document_id'], unique=False)
    op.create_index('ix_change_review', 'regulatory_changes', ['review_status'], unique=False)
    op.create_index('ix_change_type', 'regulatory_changes', ['change_type'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('change_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_review_tasks_assigned_to_users')),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_review_tasks_obligation_id_obligations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_review_tasks_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_tasks'))
    )
    op.create_index('ix_review_assigned', 'review_tasks', ['assigned_to'], unique=False)
    op.create_index('ix_review_org', 'review_tasks', ['organization_id'], unique=False)
    op.create_index('ix_review_status', 'review_tasks', ['status'], unique=False)
    op.create_index('ix_review_type', 'review_tasks', ['task_type'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=20), nullable=False),
    sa.Column('regulatory_severity', sa.Float(), nullable=True),
    sa.Column('investor_impact', sa.Float(), nullable=True),
    sa.Column('deadline_proximity', sa.Float(), nullable=True),
    sa.Column('evidence_freshness', sa.Float(), nullable=True),
    sa.Column('control_coverage', sa.Float(), nullable=True),
    sa.Column('change_magnitude', sa.Float(), nullable=True),
    sa.Column('historical_gaps', sa.Float(), nullable=True),
    sa.Column('validation_uncertainty', sa.Float(), nullable=True),
    sa.Column('factor_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculation_formula', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('underlying_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_risk_scores_obligation_id_obligations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_risk_scores_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores'))
    )
    op.create_index('ix_risk_category', 'risk_scores', ['risk_category'], unique=False)
    op.create_index('ix_risk_obl', 'risk_scores', ['obligation_id'], unique=False)
    op.create_index('ix_risk_org', 'risk_scores', ['organization_id'], unique=False)
    op.create_index('ix_risk_score', 'risk_scores', ['overall_score'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('validator_name', sa.String(length=100), nullable=False),
    sa.Column('validator_type', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_validation_results_obligation_id_obligations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_results'))
    )
    op.create_index('ix_validation_obl', 'validation_results', ['obligation_id'], unique=False)
    op.create_index('ix_validation_run', 'validation_results', ['extraction_run_id'], unique=False)
    op.create_table('evidence_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('evidence_requirement_id', sa.UUID(), nullable=True),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('MISSING', 'PENDING_REVIEW', 'VALID', 'STALE', 'INSUFFICIENT', 'REJECTED', name='evidencestatus'), nullable=False),
    sa.Column('freshness_state', sa.String(length=50), nullable=True),
    sa.Column('verification_state', sa.String(length=50), nullable=True),
    sa.Column('mapping_confidence', sa.Float(), nullable=True),
    sa.Column('review_decision', sa.String(length=50), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapping_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_requirement_id'], ['evidence_requirements.id'], name=op.f('fk_evidence_artifacts_evidence_requirement_id_evidence_requirements')),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_evidence_artifacts_obligation_id_obligations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evidence_artifacts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_evidence_artifacts_owner_id_users')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_evidence_artifacts_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_artifacts'))
    )
    op.create_index('ix_evidence_hash', 'evidence_artifacts', ['sha256_hash'], unique=False)
    op.create_index('ix_evidence_obl', 'evidence_artifacts', ['obligation_id'], unique=False)
    op.create_index('ix_evidence_org', 'evidence_artifacts', ['organization_id'], unique=False)
    op.create_index('ix_evidence_req', 'evidence_artifacts', ['evidence_requirement_id'], unique=False)
    op.create_index('ix_evidence_status', 'evidence_artifacts', ['status'], unique=False)
    op.create_table('impact_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('affected_entity_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_departments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_controls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_processes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_calendar_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['regulatory_changes.id'], name=op.f('fk_impact_assessments_change_id_regulatory_changes')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_impact_assessments_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_assessments'))
    )
    op.create_index('ix_impact_change', 'impact_assessments', ['change_id'], unique=False)
    op.create_index('ix_impact_org', 'impact_assessments', ['organization_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_task_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', 'EDIT_AND_APPROVE', 'REQUEST_REPROCESSING', 'ESCALATE', name='reviewaction'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('edits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_tasks.id'], name=op.f('fk_review_decisions_review_task_id_review_tasks')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_decisions_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_decisions'))
    )
    op.create_index('ix_decision_reviewer', 'review_decisions', ['reviewer_id'], unique=False)
    op.create_index('ix_decision_task', 'review_decisions', ['review_task_id'], unique=False)
    op.create_table('evidence_audit_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_artifact_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_evidence_audit_entries_actor_id_users')),
    sa.ForeignKeyConstraint(['evidence_artifact_id'], ['evidence_artifacts.id'], name=op.f('fk_evidence_audit_entries_evidence_artifact_id_evidence_artifacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_audit_entries'))
    )
    op.create_index('ix_evaudit_artifact', 'evidence_audit_entries', ['evidence_artifact_id'], unique=False)
    op.create_index('ix_evaudit_timestamp', 'evidence_audit_entries', ['timestamp'], unique=False)
    op.create_table('obligation_evidence_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('evidence_artifact_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_artifact_id'], ['evidence_artifacts.id'], name=op.f('fk_obligation_evidence_mappings_evidence_artifact_id_evidence_artifacts')),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_obligation_evidence_mappings_obligation_id_obligations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_obligation_evidence_mappings_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obligation_evidence_mappings'))
    )
    op.create_index('ix_oem_evidence', 'obligation_evidence_mappings', ['evidence_artifact_id'], unique=False)
    op.create_index('ix_oem_obl', 'obligation_evidence_mappings', ['obligation_id'], unique=False)
    op.create_index('ix_oem_org', 'obligation_evidence_mappings', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_oem_org', table_name='obligation_evidence_mappings')
    op.drop_index('ix_oem_obl', table_name='obligation_evidence_mappings')
    op.drop_index('ix_oem_evidence', table_name='obligation_evidence_mappings')
    op.drop_table('obligation_evidence_mappings')
    op.drop_index('ix_evaudit_timestamp', table_name='evidence_audit_entries')
    op.drop_index('ix_evaudit_artifact', table_name='evidence_audit_entries')
    op.drop_table('evidence_audit_entries')
    op.drop_index('ix_decision_task', table_name='review_decisions')
    op.drop_index('ix_decision_reviewer', table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index('ix_impact_org', table_name='impact_assessments')
    op.drop_index('ix_impact_change', table_name='impact_assessments')
    op.drop_table('impact_assessments')
    op.drop_index('ix_evidence_status', table_name='evidence_artifacts')
    op.drop_index('ix_evidence_req', table_name='evidence_artifacts')
    op.drop_index('ix_evidence_org', table_name='evidence_artifacts')
    op.drop_index('ix_evidence_obl', table_name='evidence_artifacts')
    op.drop_index('ix_evidence_hash', table_name='evidence_artifacts')
    op.drop_table('evidence_artifacts')
    op.drop_index('ix_validation_run', table_name='validation_results')
    op.drop_index('ix_validation_obl', table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index('ix_risk_score', table_name='risk_scores')
    op.drop_index('ix_risk_org', table_name='risk_scores')
    op.drop_index('ix_risk_obl', table_name='risk_scores')
    op.drop_index('ix_risk_category', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('ix_review_type', table_name='review_tasks')
    op.drop_index('ix_review_status', table_name='review_tasks')
    op.drop_index('ix_review_org', table_name='review_tasks')
    op.drop_index('ix_review_assigned', table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index('ix_change_type', table_name='regulatory_changes')
    op.drop_index('ix_change_review', table_name='regulatory_changes')
    op.drop_index('ix_change_old_doc', table_name='regulatory_changes')
    op.drop_index('ix_change_new_doc', table_name='regulatory_changes')
    op.drop_table('regulatory_changes')
    op.drop_index('ix_ocm_org', table_name='obligation_control_mappings')
    op.drop_index('ix_ocm_obl', table_name='obligation_control_mappings')
    op.drop_index('ix_ocm_control', table_name='obligation_control_mappings')
    op.drop_table('obligation_control_mappings')
    op.drop_index('ix_citation_obl', table_name='obligation_citations')
    op.drop_index('ix_citation_field', table_name='obligation_citations')
    op.drop_table('obligation_citations')
    op.drop_index('ix_evreq_org', table_name='evidence_requirements')
    op.drop_index('ix_evreq_obl', table_name='evidence_requirements')
    op.drop_table('evidence_requirements')
    op.drop_index('ix_evalresult_run', table_name='evaluation_results')
    op.drop_index('ix_evalresult_example', table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index('ix_task_status', table_name='compliance_tasks')
    op.drop_index('ix_task_org', table_name='compliance_tasks')
    op.drop_index('ix_task_obl', table_name='compliance_tasks')
    op.drop_index('ix_task_assigned', table_name='compliance_tasks')
    op.drop_table('compliance_tasks')
    op.drop_index('ix_cal_type', table_name='compliance_calendar_events')
    op.drop_index('ix_cal_org', table_name='compliance_calendar_events')
    op.drop_index('ix_cal_obl', table_name='compliance_calendar_events')
    op.drop_index('ix_cal_date', table_name='compliance_calendar_events')
    op.drop_table('compliance_calendar_events')
    op.drop_index('ix_obl_status', table_name='obligations')
    op.drop_index('ix_obl_risk', table_name='obligations')
    op.drop_index('ix_obl_org', table_name='obligations')
    op.drop_index('ix_obl_extraction_run', table_name='obligations')
    op.drop_index('ix_obl_doc', table_name='obligations')
    op.drop_index('ix_obl_deadline', table_name='obligations')
    op.drop_index('ix_obl_confidence', table_name='obligations')
    op.drop_index('ix_obl_clause', table_name='obligations')
    op.drop_table('obligations')
    op.drop_index('ix_invocation_task', table_name='model_invocations')
    op.drop_index('ix_invocation_provider', table_name='model_invocations')
    op.drop_index('ix_invocation_model', table_name='model_invocations')
    op.drop_index('ix_invocation_agent', table_name='model_invocations')
    op.drop_table('model_invocations')
    op.drop_index('ix_evalex_dataset', table_name='evaluation_examples')
    op.drop_table('evaluation_examples')
    op.drop_index('ix_cembed_model', table_name='clause_embeddings')
    op.drop_index('ix_cembed_doc', table_name='clause_embeddings')
    op.drop_index('ix_cembed_clause', table_name='clause_embeddings')
    op.drop_table('clause_embeddings')
    op.drop_index('ix_step_type', table_name='agent_steps')
    op.drop_index('ix_step_agent_run', table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index('ix_event_type', table_name='workflow_events')
    op.drop_index('ix_event_timestamp', table_name='workflow_events')
    op.drop_index('ix_event_run', table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index('ix_clause_type', table_name='clauses')
    op.drop_index('ix_clause_section', table_name='clauses')
    op.drop_index('ix_clause_parent', table_name='clauses')
    op.drop_index('ix_clause_doc', table_name='clauses')
    op.drop_table('clauses')
    op.drop_index('ix_agent_run_status', table_name='agent_runs')
    op.drop_index('ix_agent_run_name', table_name='agent_runs')
    op.drop_index('ix_agent_run_extraction', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_gedge_type', table_name='graph_edges')
    op.drop_index('ix_gedge_target_type', table_name='graph_edges')
    op.drop_index('ix_gedge_target', table_name='graph_edges')
    op.drop_index('ix_gedge_source_type', table_name='graph_edges')
    op.drop_index('ix_gedge_source', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index('ix_run_type', table_name='extraction_runs')
    op.drop_index('ix_run_status', table_name='extraction_runs')
    op.drop_index('ix_run_org', table_name='extraction_runs')
    op.drop_index('ix_run_doc', table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index('ix_section_parent', table_name='document_sections')
    op.drop_index('ix_section_doc', table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index('ix_docrel_type', table_name='document_relationships')
    op.drop_index('ix_docrel_target', table_name='document_relationships')
    op.drop_index('ix_docrel_source', table_name='document_relationships')
    op.drop_table('document_relationships')
    op.drop_index('ix_page_doc', table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index('ix_doc_type', table_name='regulatory_documents')
    op.drop_index('ix_doc_status', table_name='regulatory_documents')
    op.drop_index('ix_doc_ref', table_name='regulatory_documents')
    op.drop_index('ix_doc_org', table_name='regulatory_documents')
    op.drop_index('ix_doc_hash', table_name='regulatory_documents')
    op.drop_index('ix_doc_domain', table_name='regulatory_documents')
    op.drop_table('regulatory_documents')
    op.drop_index('ix_refresh_token_user', table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_expires', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_process_org', table_name='processes')
    op.drop_table('processes')
    op.drop_index('ix_membership_user', table_name='organization_memberships')
    op.drop_index('ix_membership_org', table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index('ix_gnode_type_entity', table_name='graph_nodes')
    op.drop_index('ix_gnode_type', table_name='graph_nodes')
    op.drop_index('ix_gnode_org', table_name='graph_nodes')
    op.drop_index('ix_gnode_entity', table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index('ix_evalrun_status', table_name='evaluation_runs')
    op.drop_index('ix_evalrun_dataset', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('ix_control_status', table_name='controls')
    op.drop_index('ix_control_org', table_name='controls')
    op.drop_index('ix_control_dept', table_name='controls')
    op.drop_table('controls')
    op.drop_index('ix_audit_user', table_name='audit_events')
    op.drop_index('ix_audit_timestamp', table_name='audit_events')
    op.drop_index('ix_audit_resource', table_name='audit_events')
    op.drop_index('ix_audit_org', table_name='audit_events')
    op.drop_index('ix_audit_action', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_active', table_name='users')
    op.drop_table('users')
    op.drop_table('regulatory_sources')
    op.drop_index('ix_prompt_task', table_name='prompt_versions')
    op.drop_index('ix_prompt_name_version', table_name='prompt_versions')
    op.drop_index('ix_prompt_active', table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.drop_index('ix_organizations_active', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_evalds_type', table_name='evaluation_datasets')
    op.drop_index('ix_evalds_active', table_name='evaluation_datasets')
    op.drop_table('evaluation_datasets')
    # ### end Alembic commands ###
