"""phase2_add_diff_fields_and_diff_runs

Revision ID: e4b4305debd7
Revises: 6ebd241e922e
Create Date: 2026-08-08 16:29:59.781378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4b4305debd7'
down_revision: Union[str, None] = '6ebd241e922e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum types first: add_column (unlike create_table) does NOT auto-create them.
    bind = op.get_bind()
    materialitylevel = postgresql.ENUM('NONE', 'LOW', 'MEDIUM', 'HIGH', name='materialitylevel')
    diffrunstatus = postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='diffrunstatus')
    materialitylevel.create(bind, checkfirst=True)
    diffrunstatus.create(bind, checkfirst=True)

    op.create_table('diff_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('old_document_id', sa.UUID(), nullable=False),
    sa.Column('new_document_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='diffrunstatus', create_type=False), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matcher_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['new_document_id'], ['regulatory_documents.id'], name=op.f('fk_diff_runs_new_document_id_regulatory_documents')),
    sa.ForeignKeyConstraint(['old_document_id'], ['regulatory_documents.id'], name=op.f('fk_diff_runs_old_document_id_regulatory_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diff_runs'))
    )
    op.create_index('ix_diffrun_new_doc', 'diff_runs', ['new_document_id'], unique=False)
    op.create_index('ix_diffrun_old_doc', 'diff_runs', ['old_document_id'], unique=False)
    op.create_index('ix_diffrun_status', 'diff_runs', ['status'], unique=False)
    op.add_column('regulatory_changes', sa.Column('diff_run_id', sa.UUID(), nullable=True))
    op.add_column('regulatory_changes', sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('regulatory_changes', sa.Column('similarity_score', sa.Float(), nullable=True))
    op.add_column('regulatory_changes', sa.Column('materiality', postgresql.ENUM('NONE', 'LOW', 'MEDIUM', 'HIGH', name='materialitylevel', create_type=False), nullable=True))
    op.add_column('regulatory_changes', sa.Column('materiality_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('regulatory_changes', sa.Column('requires_confirmation', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index('ix_change_diff_run', 'regulatory_changes', ['diff_run_id'], unique=False)
    op.create_index('ix_change_materiality', 'regulatory_changes', ['materiality'], unique=False)
    op.create_foreign_key(op.f('fk_regulatory_changes_diff_run_id_diff_runs'), 'regulatory_changes', 'diff_runs', ['diff_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_regulatory_changes_diff_run_id_diff_runs'), 'regulatory_changes', type_='foreignkey')
    op.drop_index('ix_change_materiality', table_name='regulatory_changes')
    op.drop_index('ix_change_diff_run', table_name='regulatory_changes')
    op.drop_column('regulatory_changes', 'requires_confirmation')
    op.drop_column('regulatory_changes', 'materiality_reasons')
    op.drop_column('regulatory_changes', 'materiality')
    op.drop_column('regulatory_changes', 'similarity_score')
    op.drop_column('regulatory_changes', 'changed_fields')
    op.drop_column('regulatory_changes', 'diff_run_id')
    op.drop_index('ix_diffrun_status', table_name='diff_runs')
    op.drop_index('ix_diffrun_old_doc', table_name='diff_runs')
    op.drop_index('ix_diffrun_new_doc', table_name='diff_runs')
    op.drop_table('diff_runs')
    # Drop the enum types created for the new columns/table.
    sa.Enum(name='materialitylevel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='diffrunstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
