"use client";

import { useState } from "react";
import { FileUp, Link2, Search } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/Card";
import { api } from "@/lib/api/client";
import { DataState, useApiData } from "@/lib/api/useApiData";

export default function ControlsPage() {
  const { data, loading, error } = useApiData(async () => { const [controls, evidence] = await Promise.all([api.controls(), api.evidence()]); return { controls: controls.controls, evidence: evidence.evidence }; });
  const [search, setSearch] = useState("");
  const controls = data?.controls.filter(control => `${control.name} ${control.description || ""}`.toLowerCase().includes(search.toLowerCase())) || [];
  return <div className="space-y-6 pb-12"><div><h1 className="text-[32px] font-semibold tracking-tight">Control Library & Evidence</h1><p className="text-[var(--text-secondary)] mt-1">Persisted Tenant A control mappings and reference evidence</p></div><div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2"><Card className="h-full"><div className="p-4 border-b bg-white rounded-t-2xl"><div className="relative w-72"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[var(--text-muted)]" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search controls…" className="w-full border rounded-lg pl-10 pr-4 py-2 text-sm" /></div></div><DataState loading={loading} error={error} empty={!data || controls.length === 0}><div className="overflow-x-auto bg-white"><table className="w-full text-left"><thead><tr className="bg-[var(--surface-subtle)] text-xs uppercase text-[var(--text-secondary)]"><th className="px-6 py-3">Control</th><th className="px-6 py-3">Description</th><th className="px-6 py-3">Framework</th><th className="px-6 py-3">Mapped obligations</th></tr></thead><tbody className="divide-y text-sm">{controls.map(control => <tr key={control.id} className="hover:bg-[var(--surface-hover)]"><td className="px-6 py-4 font-mono text-[var(--primary)]">{control.control_type || control.id.slice(0, 8)}</td><td className="px-6 py-4"><p className="font-medium">{control.name}</p><p className="text-xs text-[var(--text-secondary)] mt-1">{control.source_topic || control.department || "—"}</p></td><td className="px-6 py-4">{control.framework || "—"}</td><td className="px-6 py-4"><span className="flex items-center gap-1"><Link2 size={14} />{control.mapped_obligations}</span></td></tr>)}</tbody></table></div></DataState></Card></div><Card><CardHeader className="border-b"><CardTitle>Evidence Ledger</CardTitle><CardDescription>Recent persisted evidence artifacts</CardDescription></CardHeader><CardContent className="pt-6 space-y-3"><button disabled className="w-full py-6 border-2 border-dashed rounded-xl flex flex-col items-center text-[var(--text-muted)]"><FileUp className="w-7 h-7 mb-2" /><span className="text-sm">Upload not enabled</span></button><DataState loading={loading} error={error} empty={!data || data.evidence.length === 0}>{data?.evidence.map(item => <div key={item.id} className="p-3 border rounded-lg"><p className="text-sm font-medium truncate">{item.file_name}</p><p className="text-xs text-[var(--text-secondary)] mt-1">{item.freshness_state || item.status} · valid until {item.valid_until || "—"}</p></div>)}</DataState></CardContent></Card></div></div>;
}
