"use client";

import { useState } from "react";
import { Card, CardContent } from "@/components/ui/Card";
import { api, Posture } from "@/lib/api/client";
import { DataState, useApiData } from "@/lib/api/useApiData";

type Adoption = { changes: Array<{ gap_key: string; reference: string; title: string; severity: string; adoption_percentage: number }> };
type Gap = { gap: { gap_key: string; severity: string }; affected_intermediaries: number; intermediaries: Array<{ name: string; seeded: boolean; coverage_percentage: number; gap_types: string[] }> };

export default function SupervisoryPage() {
  const { data, loading, error } = useApiData<Posture>(api.posture);
  const { data: adoption } = useApiData<Adoption>(() => data ? api.adoption(data.latest_circular.circular_id) as Promise<Adoption> : Promise.resolve({ changes: [] }), [data?.latest_circular.circular_id]);
  const [gap, setGap] = useState<Gap | null>(null);
  const drilldown = async (key: string) => setGap(await api.gap(key) as Gap);
  return <div className="space-y-6 pb-12"><div><h1 className="text-[32px] font-semibold tracking-tight">Supervisory View</h1><p className="text-[var(--text-secondary)] mt-1">Aggregate market posture; seeded tenants are explicitly labelled.</p></div><DataState loading={loading} error={error} empty={!data || data.intermediaries.length === 0}><div className="grid grid-cols-1 lg:grid-cols-4 gap-6"><Rollup label="Intermediaries" value={data?.market_rollup.intermediaries} /><Rollup label="Coverage" value={data ? `${data.market_rollup.coverage_percentage}%` : undefined} /><Rollup label="Open gaps" value={data?.market_rollup.open_gaps} /><Rollup label="Circular adoption" value={data ? `${data.market_rollup.latest_circular_adoption_percentage}%` : undefined} /></div><div className="grid grid-cols-1 lg:grid-cols-3 gap-6">{data?.intermediaries.map(item => <Card key={item.intermediary_id}><CardContent className="p-5"><div className="flex justify-between"><h2 className="font-semibold">{item.name}</h2>{item.seeded && <span className="text-[10px] uppercase font-bold px-2 py-1 bg-[#FFFBEB] text-[#D97706] rounded">Seeded</span>}</div><p className="text-3xl font-semibold mt-5">{item.coverage.percentage}%</p><p className="text-xs text-[var(--text-secondary)] mt-1">{item.coverage.covered_obligations}/{item.coverage.applicable_obligations} covered</p><div className="mt-5 pt-4 border-t text-sm space-y-2"><p>Fresh: {item.evidence_freshness.valid} valid · {item.evidence_freshness.stale} stale</p><p>{item.open_gaps.total} open gaps</p><p>Adoption: {item.latest_circular_adoption.percentage}%</p></div></CardContent></Card>)}</div><Card><CardContent className="p-5"><h2 className="font-semibold">Circular adoption tracker</h2><p className="text-sm text-[var(--text-secondary)] mt-1">{data?.latest_circular.title || "Latest circular"}</p><div className="mt-5 space-y-3">{adoption?.changes.map(change => <button key={change.gap_key} onClick={() => void drilldown(change.gap_key)} className="w-full text-left p-4 border rounded-xl hover:bg-[var(--surface-hover)] flex justify-between"><span>{change.reference} · {change.title}</span><span className="font-mono">{change.adoption_percentage}%</span></button>)}</div></CardContent></Card>{gap && <Card><CardContent className="p-5"><div className="flex justify-between"><h2 className="font-semibold">Gap drilldown</h2><button onClick={() => setGap(null)} className="text-sm text-[var(--primary)]">Close</button></div><p className="text-sm mt-2">{gap.affected_intermediaries} affected intermediaries</p><div className="mt-4 space-y-2">{gap.intermediaries.map(item => <p key={item.name} className="text-sm">{item.name}{item.seeded ? " (seeded)" : ""} · {item.coverage_percentage}% coverage · {item.gap_types.join(", ")}</p>)}</div></CardContent></Card>}</DataState></div>;
}
function Rollup({ label, value }: { label: string; value: string | number | undefined }) { return <Card><CardContent className="p-5"><p className="text-sm text-[var(--text-secondary)]">{label}</p><p className="text-3xl font-semibold mt-3">{value ?? "—"}</p></CardContent></Card>; }
